### ISSUE TITLE
Doesn't support advanced sorting function like _geoPoint

### ISSUE THREAD

**Issue by LaysDragon** [riccox/meilisearch-ui#103]
**Describe the bug**
When enter a advanced sorting function include comma,its split the sorting function in half and turn into invalid query argument.

**To Reproduce**
1. Enter `_geoPoint(0.0, 0.0):asc` into sorting field.

**Expected behavior**
It should able to recognized the comma in advanced function or have some string escaping feature to deal with its.

**Screenshots**
![image](https://github.com/riccox/meilisearch-ui/assets/10185394/c993cc24-ed79-4b4f-bd30-60277cc70f10)

**Environments (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Meili 1.5.1

**Comment by riccox** [comment]
@LaysDragon Thanks!
Fixed in new release version [v0.6.11](https://github.com/riccox/meilisearch-ui/releases/tag/v0.6.11).

It will take some time to run ci, you can try online demo & latest docker image after ci finished.
