### ISSUE TITLE
Add a Search Analytics dashboard

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#104]
There is currently no search data, and the current core does not know whether it supports the development of search analysis dashboards:

refer to： https://roadmap.meilisearch.com/c/129-search-analytics

**Comment by riccox** [comment]
@Avey777 Thx!

The feature mentioned in the link needs to integrate server related functions to achieve, at this stage, the application is only considered to be used in the pure client scenario, and cannot realize the search request analysis features.
