### ISSUE TITLE
Donation entrance

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#105]
When I was preparing to donate, I found that I didn’t have a credit card. I recently registered a credit card and couldn’t find the donation entrance.

Not because I have much money, just because I want to use this project, and I want to give the author spiritual encouragement in this way.

It would be great if you could specify functions to reward. If there is an urgently needed function, you can reward development for it.

**Comment by riccox** [comment]
Hi, @Avey777 
Thx for your love! 
I will give BUG issues high development priority in this project, followed by functional enhancement.
You can [buy me a coffee](https://www.buymeacoffee.com/riccoxie) if you wanna donate this project.

**Comment by Avey777** [comment]
![image](https://github.com/riccox/meilisearch-ui/assets/35259040/6b531820-1def-453d-ac9c-dea729869bf0)
