### ISSUE TITLE
Visual enhancement and fixed document position

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#106]
https://blog.meilisearch.com/promoted-search-results-with-react-instantsearch/?utm_campaign=oss&utm_source=productboard&utm_medium=portal

https://blog.meilisearch.com/promoted-search-results-with-react-instantsearch/?utm_campaign=oss&utm_source=productboard&utm_medium=portal

https://github.com/orgs/meilisearch/discussions/546

**Comment by riccox** [comment]
@Avey777 Thx!

This feature will not be considered to be added in next major version.

Because the feature is designed to use in end-user scenario.
But this app I designed is mainly used by developers & administrators.
