### ISSUE TITLE
The input in the searchForm causes the page to flicker and the input box to lose focus

### ISSUE THREAD

**Issue by rrbe** [riccox/meilisearch-ui#108]
**Describe the bug**
I'm not sure if this qualifies as a bug, but the user experience is evidently not great. This issue is present in versions 0.6.9 and 0.6.10; it wasn't present in version 0.6.4.

**To Reproduce**
1. Go to '/ins/1/index/{indexName}'
2. Input in 'any of the searchForm's input fields'
3. See page flicker

**Expected behavior**
The page doesn't flicker; it only changes the value in the search area

**Screenshots**

**Environments (please complete the following information):**
 - OS: macOS m1
 - Browser: Chrome 120.0.6099.129
 - Version: 0.6.9 / 0.6.10

**Additional context**

**Comment by riccox** [comment]
@rrbe Try latest version v0.6.11.

**Comment by rrbe** [comment]
it works, thank you!
