### ISSUE TITLE
能否支持连接IP:端口？

### ISSUE THREAD

**Issue by dianso** [riccox/meilisearch-ui#110]
我之前绑定了个域名，正常，但是用IP+端口就连不上

**Comment by LaysDragon** [comment]
連不上也會有很多種錯誤，沒log就只能瞎猜😂

**Comment by dianso** [comment]
> 這玩意走的是瀏覽器支持的協議不可能不支持，連不上也有很多種錯誤，沒log就只能瞎猜。另外像chrome瀏覽器預設不允許不安全連線要注意(從https頁面連到http在chrome上預設被禁止)😂

好像是这样，必须用域名+ssl证书https访问

**Comment by riccox** [comment]
是指的这个应用还是 meilisearch 实例？

**Comment by LaysDragon** [comment]
> > 這玩意走的是瀏覽器支持的協議不可能不支持，連不上也有很多種錯誤，沒log就只能瞎猜。另外像chrome瀏覽器預設不允許不安全連線要注意(從https頁面連到http在chrome上預設被禁止)😂
> 
> 好像是这样，必须用域名+ssl证书https访问

Chrome 可以到該域名的網站設定調整`不安全的內容`為`允許`作為臨時措施

**Comment by JQiue** [comment]
> > 這玩意走的是瀏覽器支持的協議不可能不支持，連不上也有很多種錯誤，沒log就只能瞎猜。另外像chrome瀏覽器預設不允許不安全連線要注意(從https頁面連到http在chrome上預設被禁止)😂
> 
> 好像是这样，必须用域名+ssl证书https访问

你需要贴出控制台信息，不然就是瞎猜

**Comment by dianso** [comment]
> > > 這玩意走的是瀏覽器支持的協議不可能不支持，連不上也有很多種錯誤，沒log就只能瞎猜。另外像chrome瀏覽器預設不允許不安全連線要注意(從https頁面連到http在chrome上預設被禁止)😂
> > 
> > 
> > 好像是这样，必须用域名+ssl证书https访问
> 
> 你需要贴出控制台信息，不然就是瞎猜

任何一个有电脑的人都能复现

**Comment by riccox** [comment]
@dianso 已测试，无法复现，请检查你的网络或浏览器设置，给出更详细的 debug 信息。

**Comment by dianso** [comment]
刚测试了，不行

很简单啊，就是IP+端口不行
域名+ssl可以

**Comment by riccox** [comment]
Reopened due to bug exist.

**Comment by riccox** [comment]
@dianso Fixed in latest version v0.9.2.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
