### ISSUE TITLE
The search box refreshes when typing, making it impossible to work properly

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#112]
**Describe the bug**
Search input box and filter, refresh the page every time a word is entered. This interaction makes it difficult to use the search function properly

**Environments (please complete the following information):**
 - OS: macOS
 - Browser  edge
 - Version  0.6.12

**Comment by riccox** [comment]
@Avey777 Pls provide more informations.
I can not reproduce it by using v0.6.12 with official demo dataset.

**Comment by Avey777** [comment]
https://github.com/riccox/meilisearch-ui/assets/35259040/3de7cacf-65e6-431d-95fb-105b6d1e44f7

The network is a little slower, this loading effect. It makes people feel very uncomfortable, mainly because the interaction here is inappropriate.

![image](https://github.com/riccox/meilisearch-ui/assets/35259040/86f1d279-771f-46c1-84e1-08b9076eefdd)

**Comment by Avey777** [comment]
> @Avey777 Pls provide more informations. I can not reproduce it by using v0.6.12 with official demo dataset.

Can this be optimized?

**Comment by riccox** [comment]
@Avey777 Are you using online version to reproduce this？
I can't reproduce same problem with that.

**Comment by Avey777** [comment]
> @Avey777 Are you using online version to reproduce this？ I can't reproduce same problem with that.

You can try slowing down your Internet connection. I am using the Edge browser.
https://meilisearch-ui-git-main-avey777.vercel.app/

**Comment by Avey777** [comment]
I think it would be better to just turn off search while typing and search again when clicking the Search button

**Comment by riccox** [comment]
@Avey777 Thx!
Reproduced this bug in slow internet connection mode already.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
