### ISSUE TITLE
Sorting results at search time

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#115]
Add Sort feature

https://www.meilisearch.com/docs/learn/fine_tuning_results/sorting

![image](https://github.com/riccox/meilisearch-ui/assets/35259040/7d7b9e2c-3e0b-4d9a-80aa-a7f13cdc3333)

**Comment by riccox** [comment]
@Avey777 Sort at search time feature had been added in early version already.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
