### ISSUE TITLE
Adding a new key with UID

### ISSUE THREAD

**Issue by rbozan** [riccox/meilisearch-ui#118]
![image](https://github.com/riccox/meilisearch-ui/assets/7997154/f8f97dae-f2d3-404b-8b60-15c8a2adf4d3)
https://www.meilisearch.com/docs/reference/api/keys#body

The UI is missing the ability to set the `uid` field.

**Comment by riccox** [comment]
@rbozan 

The new version v0.7.1 has been published. Hope you can try it.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
