### ISSUE TITLE
Index page isn't scrollable

### ISSUE THREAD

**Issue by ahmednfwela** [riccox/meilisearch-ui#12]
This area isn't scrollable, so when you have a lot of indexes, you can't see them all 
![image](https://user-images.githubusercontent.com/63286031/222776561-0bbbac09-124d-4805-a1c3-b8070aee2fec.png)

cc @riccox

**Comment by riccox** [comment]
Thanks!
Fixed in new release version [v0.1.2](https://github.com/riccox/meilisearch-ui/releases/tag/v0.1.2)
