### ISSUE TITLE
Add search terms to the task dashboard

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#122]
1. Start time range filtering
2. End time range filtering
3. Index filtering

**Comment by riccox** [comment]
@Avey777 

The new version v0.7.1 has been published. Hope you can try it.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
