### ISSUE TITLE
Everything is all over the place

### ISSUE THREAD

**Issue by CC52-dev** [riccox/meilisearch-ui#125]
Everything is all over the place. I would suggest having a navigation bar with all the features instead of just a couple. And also a getting started guide will be good as well.

**Comment by riccox** [comment]
@CC52-dev Hi，
Thx for your advices.
The new version ui is under developing nowadays，u will see that in short time.

**Comment by CC52-dev** [comment]
Thank you

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
