### ISSUE TITLE
tasks filter status no result，There are actually many tasks

### ISSUE THREAD

**Issue by mj520** [riccox/meilisearch-ui#126]
**Describe the bug**

**To Reproduce**
1. tasks filter status no result，There are actually many tasks

**Expected behavior**
has result

**Screenshots**
![image](https://github.com/user-attachments/assets/80a98966-2fa1-4398-958a-8c5fd0f484f3)

**Environments (please complete the following information):**
 - OS: windows10
 - Browser chrome
 - Version v0.6.16

**Additional context**
status filter    no request or request from = int  error，no result

**Comment by riccox** [comment]
@mj520 Could u paste more information about your requests (payload & responses) which applied filters.

**Comment by mj520** [comment]
When there are a large number of tasks that have already been queued for execution and have already been completed, if the previous tasks are all queued, if the switches to completed or executing are empty, and if several tasks are loaded to completed or executing first, the switches have data but are still missing and cannot be scrolled, it means that only the current data is filtered
You can compare it with the interface or see if data is requested when switching

**Comment by riccox** [comment]
@mj520 Thx! I'm developing a brand new version of this admin panel, try to fix this in next major version, hope u can try that at that time.

**Comment by riccox** [comment]
Closed due to no response.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
