### ISSUE TITLE
Add meilisearch version

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#133]
I'd like to see the version here:

![image](https://github.com/user-attachments/assets/262e7121-667b-4e1f-83c6-90c3bc8518c6)

Like it is with the mini-dashboard included in meilisearch:

![image](https://github.com/user-attachments/assets/bf88198f-7dc0-493b-ad6c-3ff28fa4d6e0)

**Comment by riccox** [comment]
Closed as completed.
