### ISSUE TITLE
show facets rather than fields (or a separate page)

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#135]
Showing all the fields is overwhelming.  What I'm most interested in is the filterable fields (aka facets).  

![image](https://github.com/user-attachments/assets/4b336f13-d95e-41f6-b878-f706bccf5e05)

The graph shows all the display fields, what i want is the filterable attributes:

![image](https://github.com/user-attachments/assets/b8373101-0ba0-4086-adf7-20cc50bc0183)

**Comment by riccox** [comment]
Show top 10 facets.

Closed as completed.
