### ISSUE TITLE
React Error 

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#136]
![image](https://github.com/user-attachments/assets/3f34f682-5363-419d-95db-68f0862b4083)

https://meilisearch-ui.riccox.com/ins/2/index/mus_px_walters_obj/documents

Please contact me at tacman@gmail.com and I can give you the ApiKey to access my indexes.  I have no confidential data in the indexes.  

What a great tool, thanks for releasing it!

**Comment by riccox** [comment]
@tacman Mail you already.

**Comment by tacman** [comment]
Looks like it's fixed now, thanks!

**Comment by tacman** [comment]
I should specific that from the link above, you need to click on the "Table" button in order to see the error.
