### ISSUE TITLE
Add "sparse/detail" toggle switch

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#138]
Many of the records I index are empty.  I'd like to see option to ignore showing fields with null or blank values.

![image](https://github.com/user-attachments/assets/9ab04aa2-b6ab-4beb-ab42-f478e1c5f109)

A switch like auto-refresh, but that says "Hide empty fields" (or "Show empty fields", and make the default to hide them).  

I should probably remove the empty fields when doing in the indexing, and then handle missing fields in my code.  Hmm.  I wonder what best practices are.

![image](https://github.com/user-attachments/assets/bafafa68-7160-446f-8bc9-208a653d1940)

**Comment by riccox** [comment]
@tacman Thx for your issue!

I'd like to discuss if this feature is really in need.

Empty string or null value is meaningful in some scenarios.
This feature will make developer confused if they does not realize this.

So I will consider this feature vary cautiously.

**Comment by tacman** [comment]
yeah, makes sense.  I'll try adding something to my code to get rid of null fields before indexing.

**Comment by tacman** [comment]
In the end, I tweaked my code to remove nulls and blanks before passing the record to the indexer.

```php
    // based on https://stackoverflow.com/questions/4352203/any-php-function-that-will-strip-properties-of-an-object-that-are-null
    public static function cleanNullsOfObject(&$object) {
        foreach ($object as $property => &$value) {
            if (is_object($value)) {
                self::cleanNullsOfObject($value);
                if (empty(get_object_vars($value))) {
                    unset($object->$property);
                }
            }
            // check for array of objects
            if (is_array($value) && array_is_list($value)) {
                foreach ($value as $val) {
                    if (is_object($val)) {
                        self::cleanNullsOfObject($val);
                    }
                }

            }
            if (is_null($value) || ( (is_string($value) && $value === '') || is_array($value) && empty($value))) {
                unset($object->$property);
            }
        }
    }
```
