### ISSUE TITLE
Indicate filterable, sortable and searchable keys 

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#141]
When displaying the keys, it'd be helpful to know which fields are sortable, searchable and filterable.

![image](https://github.com/user-attachments/assets/5648b467-c908-4b76-acaa-725716c80918)

That is, in the case above, image_count is a filterable attribute, so if that field were in a different color or font, or had a little filter icon next to it, it'd be more obvious.

![image](https://github.com/user-attachments/assets/21dc2bc5-59e8-4116-96b7-97b4a4b14138)

In my case, the searchable fields are nested within a _translations key, which is a bit complicated and application-specific.  But if it weren't, I'd want to know which fields were searchable.  

Thanks for your consideration.

**Comment by riccox** [comment]
Closed as completed.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
