### ISSUE TITLE
Finished at/Started At should be empty if not finish/started

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#142]
![image](https://github.com/user-attachments/assets/10c96db5-1bf6-4215-9ccf-6c4734eaa5b5)

The "Finished at" time should be empty here.  If it enqueued, so should the start time.

Duration _could_ be the time spent so far, and if it used that stimulus_timeago, it would automatically increment the seconds in realtime.  But that's probably not worth it, auto-refresh exists for that purpose.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
