### ISSUE TITLE
Change duration to ms

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#144]
I would rather see this number as an right-justified integer, in milliseconds, e.g. 98 in this case.

![image](https://github.com/user-attachments/assets/644ce69f-de4c-460d-bf52-347d20ae82b4)

**Comment by riccox** [comment]
Closed as completed.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
