### ISSUE TITLE
Link to task list filtered by index

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#145]
![image](https://github.com/user-attachments/assets/1233caa1-3c75-4d6c-8637-f7bca9ca76b1)

I would like to see a link here that goes to the task page, but filtered by index, since often I want to see the tasks related to a specific index.

![image](https://github.com/user-attachments/assets/b3879120-1c18-4ae7-acad-d3680a6ce2e2)

Ideally, I'd be able to pass the index name to the URL as well, so I could link to it from another site, which I'll need to do because of the number of indexes I use.

**Comment by riccox** [comment]
Closed as completed.
