### ISSUE TITLE
Add "Discussions" to this repo?

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#147]
This is neither a bug report nor feature request, would you consider a "Discussions" section?

I'm trying to solve the problem of managing my own indexes and linking directly to the index / tasks pages.  Since I'm using Symfony, my strategy is to create a special router that points to the /dist/index.html page, and manage the indexes in my own database rather than via the API.

This may also allow me to manage multiple webhooks, since meili's webhooks are limited to a single webhook at the server level.

I don't have much experience with deploying react apps, so I'm hacking a bit to make it work.  My current plan:

* run `pnpm build` to create the /dist 
* copy the generated assets to a Symfony bundle
* copy the dist/index.html to index.html.twig and map the asset calls to their twig equivalent
* create a Symfony route that matches everything and passes it to the index file above.  (Otherwise, it tries to find it it on the server, and since meilisearch-ui is a SPA and has its own routing, it needs to go directly here).

I have a Symfony bundle that sort of does this, but with https://github.com/kaermorchen/meiliadmin, which is outdated and doesn't support the newer filters.  

I'll keep you updated on my progress.  I quite like this library, and appreciate your responsiveness to my issues.  Thanks again.

**Comment by tacman** [comment]
I've set up my web server as described above, but I'm getting a "Not Found" error.  I'm pretty sure this is because I have a path to get the the server (rather than a dedicated port), so my-server/riccox/ is serving the index.html file, but the js is looking for the instance or whatever in the path at the root.

Is there a way to set the base path to something besides "/", so that your js knows to where to start looking for the route?

**Comment by riccox** [comment]
@tacman Thx!

Discussions section had been opened now.

If you wanna to configure base path of this app, just check out gh-40.
