### ISSUE TITLE
Direct link to a search query

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#148]
I'd like to link directly to a search.  That is, I'd like to pre-fill this form (and results):

![image](https://github.com/user-attachments/assets/24503c5c-8400-4d82-b718-3ab6891dc7f7)

This would have the benefit of allowing a search to be bookmarkable, if you added the search reuqest as a querystring when the user clicks on the "Search" button in the string above.

**Comment by riccox** [comment]
Closed as completed.
