### ISSUE TITLE
add created, last updated, in timeago format, to listing

### ISSUE THREAD

**Issue by tacman** [riccox/meilisearch-ui#149]
![image](https://github.com/user-attachments/assets/2d1fc2ed-1a1b-4beb-b1e9-c8653636b9d2)

Can you add Last updated and Created at to this screen?  And if there's room, maybe on hover a link to setttings, and tasks?  Right now, it only links to documents, which is great, but sometime I want to go right to the tasks or settings.   

Obviously, not critical, but seems like a nice enhancement.

**Comment by riccox** [comment]
`Last updated` & `Created at` attributes will not be added into this card place.

Because the API request of this list component using does not response these data.

And I think that it will be huge cost of network requests if I add these informations only for 2 datetimes.

**Comment by tacman** [comment]
/stats doesn't return it, but the initial index does.

**Comment by riccox** [comment]
@tacman Thx!

I reviewed that.

It will be added soon.

**Comment by riccox** [comment]
Closed as completed.

**Comment by riccox** [comment]
@tacman v0.9.1 has added this feature.

But you should pay attention to real response of index list request.

It will response `null` value at `createdAt` & `updatedAt` fields sometime due to unknown reason.
