### ISSUE TITLE
文档搜索结果转成表格视图时出错

### ISSUE THREAD

**Issue by ZimaBlueee** [riccox/meilisearch-ui#154]
1. 点击这里的表格
![图片](https://github.com/user-attachments/assets/bb8cf20a-120e-47f1-9061-14c5bdfc5c82)

2. 报错
![图片](https://github.com/user-attachments/assets/f9241761-321b-4618-af4d-33122366d56a)

完整报错信息
```
Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BeducationalExperience%2C%20professionalTitleInfo%2C%20studiesExperience%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

**Comment by riccox** [comment]
@ZimaBlueee 

可尝试使用开发步骤启动开发服务器复现 以获取完整错报错信息.

或者请邮件私发我能够复现的最小 demo 实例连接信息.

**Comment by ZimaBlueee** [comment]
@riccox 
后续我搭建一个demo给你吧。

会不会是我的json数据结构层数过多导致的？因为我另一个索引里，文档json只有一层，是可以正常使用表格渲染的

**Comment by riccox** [comment]
Closed due to a long period of no response.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
