### ISSUE TITLE
Index sorting

### ISSUE THREAD

**Issue by neosandor** [riccox/meilisearch-ui#160]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to choose between the sorting of the Indexes by name and by Count (the number of documents it has)

**Describe the solution you'd like**
Some kind of ui element next to the search bar maybe which allows the sorting ascendant and descendant by name and count.

**Additional context**
![image](https://github.com/user-attachments/assets/eb1a8ce8-de85-4b91-92c6-efd153ef1952)

Please consider this feature!
Thank you for your work!

**Comment by riccox** [comment]
@neosandor 

Indexes List request used here is [this](https://www.meilisearch.com/docs/reference/api/indexes#list-all-indexes).

Consider this interface offered by Meilisearch official does not provide any available params to sort name or count of documents to achieve this.

I prefer your feature request after they approved this interface.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
