### ISSUE TITLE
Update document sent to 'undefined' index instead of the current one.

### ISSUE THREAD

**Issue by reinaldomendes** [riccox/meilisearch-ui#162]
Error on the URL `/ins/1/index/books/documents?q=&limit=20&offset=0&filter=&sort=` 

- First update no request sent
- Second update send update to `undefined` index

**To Reproduce**
1. Open meilisearch-ui on the browser
2. Select one index and click documents
3. Open Chrome inspector in the Network tab
4. Update the documents in JSON tab
5. You will see no PUT/PATCH request
6. Repeat step 4 with **JSON**, **Table** and **Grid**
7. You will see task created but the index is `undefined` instead current index

**Expected behavior**
Expect document update in every view tab (JSON, Grid, Table) to update the index.

**Screenshots**
![First](https://github.com/user-attachments/assets/bd802d0a-1793-4e76-895b-12b8f1a8d695)
![Second](https://github.com/user-attachments/assets/88673e09-7147-45bc-bf87-cccc948de8b1)

**Environments (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser: Brave 
 - User-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
 - Version: 1.61.114 Chromium: 120.0.6099.199 (Official Build) 
 - Docker Image: riccoxie/meilisearch-ui:v0.9.4

**Comment by riccox** [comment]
@reinaldomendes 

Fixed in latest version.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
