### ISSUE TITLE
Can't access /tasks ui

### ISSUE THREAD

**Issue by fitimvata** [riccox/meilisearch-ui#163]
Can't access https://meilisearch-ui.riccox.com/ins/1/tasks

**Screenshots**
<img width="594" alt="Screenshot 2024-10-30 at 5 45 20 PM" src="https://github.com/user-attachments/assets/d988e723-ef34-4767-815f-950ea1d53d35">

**Comment by riccox** [comment]
@fitimvata Could you paste some network request info of dev panel.

**Comment by ta3pks** [comment]
+1

**Comment by fitimvata** [comment]
@riccox today its working i don't know what happened

**Comment by fitimvata** [comment]
@riccox it happens when some tasks have status enqueued

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
