### ISSUE TITLE
2K 分辨率下，设置页面可以展示更多数据

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#168]
![image](https://github.com/user-attachments/assets/7203e9ee-7ce6-4ec1-abc4-1f8fb545f6e5)

**Comment by riccox** [comment]
Fixed in latest version.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
