### ISSUE TITLE
图片后缀名称大写时，网格模式下不展示图片

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#169]
![image](https://github.com/user-attachments/assets/c992f7c5-7d4c-4145-82ec-37b8bd320a1f)

**Comment by riccox** [comment]
Fixed in latest version.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
