### ISSUE TITLE
Settings aren't editable after last update 

### ISSUE THREAD

**Issue by ahmednfwela** [riccox/meilisearch-ui#17]
1. Go to index settings page
2. Click edit
3. Change anything (add filterable attribute for example)
4. Click save
5. this appears, and settings aren't saved
![image](https://user-images.githubusercontent.com/63286031/222881203-5a0f4bcc-2451-4fe0-86cb-ea33792779d7.png)

**Comment by ahmednfwela** [comment]
cc @riccox

**Comment by ahmednfwela** [comment]
also once this bug occurs, everytime the textbox loses focus, it escapes the json again: 
![image](https://user-images.githubusercontent.com/63286031/222881317-1f550e3f-7450-4ccb-a053-ff3d2d14b75d.png)

**Comment by riccox** [comment]
@ahmednfwela Thanks!
Fixed in new release version [v0.1.3](https://github.com/riccox/meilisearch-ui/releases/tag/v0.1.3).
BTW I will release a new version to offer more visualization support #3 for index setting in the near future.
Hope you will like that.
