### ISSUE TITLE
网格模式下，复制图片URL 的功能未真正复制到剪贴板

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#170]
![image](https://github.com/user-attachments/assets/bdcedff2-ea60-4789-bced-9d32dc3f26df)

**Comment by riccox** [comment]
@Avey777 网络模式是指？

**Comment by Avey777** [comment]
> @Avey777 网络模式是指？

 网格  
 
 其实我是过了，点击复制会提示复制成功，但去别的地方粘贴是没有内容的

**Comment by riccox** [comment]
Fixed in latest version.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
