### ISSUE TITLE
刷新页面，保持上次的文档的展示模式

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#172]
![image](https://github.com/user-attachments/assets/5af4e66a-268c-4198-a7d8-017d669beadf)

**Comment by riccox** [comment]
Added in latest version.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
