### ISSUE TITLE
文档页面，偏移为0的时候，点击下步进器 报错

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#173]
![image](https://github.com/user-attachments/assets/a72dd387-1607-4bad-bfab-830eec98b83b)

![image](https://github.com/user-attachments/assets/ede202f7-e946-447a-8256-3e8fe3a920a0)

**Comment by riccox** [comment]
Fixed in latest version.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
