### ISSUE TITLE
文档 -限制结果搜索的值为1时，点击下步进器报错

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#174]
![image](https://github.com/user-attachments/assets/a5232a02-6b90-4d2d-a79e-bcc8aaaa8ae2)

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
