### ISSUE TITLE
文档页面，希望只使用全局横向滚动条

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#175]
![image](https://github.com/user-attachments/assets/4ab2bf02-8d67-4a1a-85ba-c3e138465022)

**Comment by riccox** [comment]
此处的滚动条为表格组件在宽度溢出时使用，考虑将此处无作用的全局横向滚动条移除。

**Comment by Avey777** [comment]
> 此处的滚动条为表格组件在宽度溢出时使用，考虑将此处无作用的全局横向滚动条移除。

ok

**Comment by riccox** [comment]
Fixed in latest version.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
