### ISSUE TITLE
Add support for showRankingScore search parameter

### ISSUE THREAD

**Issue by jkobus** [riccox/meilisearch-ui#176]
It would be nice to have a small checkbox in documents view, where I can opt-in for showing the ranking score for each document. It is useful for debugging if we play around a lot with ranking rules. 

I think it would be a great addition to this fantastic UI.

https://www.meilisearch.com/docs/reference/api/search#ranking-score

**Comment by riccox** [comment]
Nice. Added into TODO.

**Comment by riccox** [comment]
Added in latest version.

**Comment by ItBayMax** [comment]
Hello, you can try using new tools: meilisearch-desktop (desktop version) or meilisearch-admin (web version). Their GitHub links are: https://github.com/ItBayMax/meilisearch-desktop and https://github.com/ItBayMax/meilisearch-admin. These tools fully implement the management and querying of the Meilisearch search engine, making them very developer-friendly.
