### ISSUE TITLE
Click the browser refresh button on the setting page, and 404 error will be reported

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#28]
![image](https://user-images.githubusercontent.com/35259040/224871762-2b72cd4c-798f-4cc3-bc2e-b7b661793ebd.png)

**Comment by riccox** [comment]
@Avey777 Thanks!
Fixed in new release version [v0.2.1](https://github.com/riccox/meilisearch-ui/releases/tag/v0.2.1)
