### ISSUE TITLE
Visualization edit the document and display the document in a more friendly Json format

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#30]
![image](https://user-images.githubusercontent.com/35259040/224916849-07109d37-770d-4ec3-9a7b-e435155514d7.png)

1. The size of the pop-up window is larger

2. Json data can be formatted, not all displayed in one line

**Comment by riccox** [comment]
@Avey777 Thanks!
Improved in new release version [v0.2.2](https://github.com/riccox/meilisearch-ui/releases/tag/v0.2.2)
