### ISSUE TITLE
Multiple display styles of documents

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#32]
1、
![image](https://user-images.githubusercontent.com/35259040/224923877-28f19dbc-724c-42b7-a7ef-257c4b31b56f.png)
2、
![image](https://user-images.githubusercontent.com/35259040/224923931-62b18967-198f-4c62-b835-7deab9d3f84c.png)

3、
![image](https://user-images.githubusercontent.com/35259040/224924093-bd475314-7ba4-4751-8a70-491eab1e6226.png)
4、
![image](https://user-images.githubusercontent.com/35259040/224924323-2f0578f3-376d-4301-81f4-1562a0bc6a84.png)

**Comment by riccox** [comment]
@Avey777

The new version v0.7.1 with multiple display styles has been published. Hope you can try it.
