### ISSUE TITLE
Ranking and Sorting Optimization

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#34]
![image](https://user-images.githubusercontent.com/35259040/225483016-b9ef89da-0407-41f1-8b57-d97fcd9cdde8.png)
rrefer to：
![image](https://user-images.githubusercontent.com/35259040/225482955-9458c874-3df9-4e1a-8609-0a773a53666b.png)
![image](https://user-images.githubusercontent.com/35259040/225483063-1bb867ee-3d02-45a2-8a6f-570159c36e73.png)

**Comment by riccox** [comment]
Closed due to incompatibility with existing versions.
