### ISSUE TITLE
The sort column error bug

### ISSUE THREAD

**Issue by NeroHin** [riccox/meilisearch-ui#36]
**Describe the bug**
I have a bug where I use the sort function in indexes and type in, and it displays an app error.
The app needs to be reloaded before it works.

**To Reproduce**
1. Go to each indexes page
2. Input everything in the sort column
3. It would display "app error and undefined reload."

**Screenshots**
![CleanShot 2023-03-31 at 09 51 12](https://user-images.githubusercontent.com/17636182/229002889-a0836994-7e3a-439c-aeb0-c9d33b3ad850.gif)

**Environments (please complete the following information):**
 - OS: MacOS Ventura 13.1
 - Browser: Brave 
 - Version: v149.128

**Comment by riccox** [comment]
@NeroHin Thanks!
Fixed in new release version [v0.2.3](https://github.com/riccox/meilisearch-ui/releases/tag/v0.2.3).
Note that it will take a while to ci build & publish.
