### ISSUE TITLE
Can not add document by using Input by editor

### ISSUE THREAD

**Issue by Sang2306** [riccox/meilisearch-ui#39]
**manually input by editor not successfully**
After input a list of object by using input by editor. It not successfully create a new document

**Comment by riccox** [comment]
Hi @Sang2306 ,
could you paste your input code or screenshots here to help me find out.

**Comment by riccox** [comment]
Hi @Sang2306 ,
Just paste some screenshots here to help me reproduce that.

**Comment by riccox** [comment]
Hi @Sang2306 
You can try same action again, and memory the task number show below, then go tasks page to check this task detail for debug,
I will close this issue if you can not give me any feedback, cause I can not reproduce this problem. i😅
