### ISSUE TITLE
Backspace in filter causes page to crash

### ISSUE THREAD

**Issue by ImLunaHey** [riccox/meilisearch-ui#4]
I go to the example movies index and put `genre=comedy` everything works.
Then if I backspace all the way to `genre=` the page shows an error message and prompts me to refresh.

Or even just typing `genr` and then hitting backspace can sometimes cause this.

![image](https://user-images.githubusercontent.com/105922175/207038046-3b211ddc-9902-45e7-9bb9-3ba02b5e1c47.png)

**Comment by riccox** [comment]
@ImLunaHey 
Hi, I have try to reproduce the error you mentioned, but everything works normally, could you describe your environment to help us find out.

reproduce record (short video):
https://user-images.githubusercontent.com/55175598/208035744-d55eba00-eb5c-4583-be41-fe3fcb8f0c91.mp4
