### ISSUE TITLE
商品的筛选功能不可用（或者是我不会使用）

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#44]
![image](https://user-images.githubusercontent.com/35259040/236724393-f8c27110-b96b-4576-b540-9c8a67bfb397.png)

这里应该是筛选部分属性的的属性值（比如 筛选某个属性是值为0的数据），但是在chrome 浏览器中 这个功能不能使用（当然也可能是我不会使用）

**Comment by riccox** [comment]
Hi @Avey777 ,
the filter input should be edit like [this official filtering expression text](https://www.meilisearch.com/docs/learn/advanced/filtering#examples) for usage.

**Comment by Avey777** [comment]
> Hi @Avey777 , the filter input should be edit like [this official filtering expression text](https://www.meilisearch.com/docs/learn/advanced/filtering#examples) for usage.

![image](https://user-images.githubusercontent.com/35259040/236785548-b71129e1-b15e-4fd0-b037-d3dd973824a6.png)
在我的筛选语句写错的情况下，可以不进入这个页面吗？ 很多时候会手误

**Comment by riccox** [comment]
> > Hi @Avey777 , the filter input should be edit like [this official filtering expression text](https://www.meilisearch.com/docs/learn/advanced/filtering#examples) for usage.
> 
> ![image](https://user-images.githubusercontent.com/35259040/236785548-b71129e1-b15e-4fd0-b037-d3dd973824a6.png) 在我的筛选语句写错的情况下，可以不进入这个页面吗？ 很多时候会手误
> 
> 可以在筛选栏下面给个文字提示就好了

Thanks, created new issue #46 and roadmap plan for this.
