### ISSUE TITLE
Not able to add instance

### ISSUE THREAD

**Issue by sahibnasirov** [riccox/meilisearch-ui#5]
![image](https://user-images.githubusercontent.com/21196576/209568752-3f067ddc-87d9-4766-9cf2-bd9c8c39bd3f.png)
not able to add local instance invalid host always

**Comment by sahibnasirov** [comment]
sorry setup works fine. just some comments 
1. Has to use full url  http://127.0.0.1:7700 without protocol it does not accept
2. masterkey has to set in your meilisearch instance,  with development environment it just return error and this cause ui error

**Comment by riccox** [comment]
Thanks, will be optimized in a later version.
