### ISSUE TITLE
Disable client side validation on the filter field

### ISSUE THREAD

**Issue by ahmednfwela** [riccox/meilisearch-ui#57]
**Describe the bug**
The filter field has many validation bugs while searching, and it doesn't support all the latest changes (like IS NULL, IS EMPTY).
so I suggest disabling the client side validation altogether and leaving only the server-side validation

**Screenshots**
![image](https://github.com/riccox/meilisearch-ui/assets/63286031/bf6d294c-b5c1-406e-951d-c1c9695065a5)
![image](https://github.com/riccox/meilisearch-ui/assets/63286031/9581c7fa-ea50-4f93-b7cd-3adb591c26ec)
![image](https://github.com/riccox/meilisearch-ui/assets/63286031/aeb53fb9-29fb-4b08-b16a-a050feaffd86)

**Environments (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version 0.4.0

cc @riccox

**Comment by riccox** [comment]
@ahmednfwela Thanks!
Fixed in new release version [v0.4.1](https://github.com/riccox/meilisearch-ui/releases/tag/v0.4.1).
Note that it will take a while to ci build & publish.

**Comment by ahmednfwela** [comment]
@riccox works perfectly! thanks for your amazing work!
