### ISSUE TITLE
Config persistence across restarts

### ISSUE THREAD

**Issue by smnbbrv** [riccox/meilisearch-ui#59]
First of all, thank you for a great tool! Exactly what I was looking for 

**Is your feature request related to a problem? Please describe.**

If I restart / lose my container, the configuration of all my instances is gone.

That's why I'd like to persist all my configs in a volume. Is there a way of doing so or the config is not stored on the file system?

**Describe the solution you'd like**

A path to mount into a docker container to store the configuration files in there

**Comment by riccox** [comment]
@smnbbrv Hi,
Thanks for your love!
The meilisearch-ui store all instances' config data inside your browser (localStorage) now, so the instance config data will be reserved if you are using the same url (domain+port) to access meilisearch-ui.
