### ISSUE TITLE
Document Download

### ISSUE THREAD

**Issue by Avey777** [riccox/meilisearch-ui#64]
It would be great if JSON files could be downloaded and shared with colleagues for the query files retrieved during troubleshooting

It would be great if you could choose the download field when downloading! Many times, only a portion of the data is needed to handle problems

**Comment by riccox** [comment]
Do u mean to download query hit results (JSON Array) with specified fields?

**Comment by Avey777** [comment]
> Do u mean to download query hit results (JSON Array) with specified fields?

yeah

**Comment by riccox** [comment]
@Avey777 

The new version v0.7.1 with new features has been published. Hope you can try it.
