### ISSUE TITLE
Tenant tokens

### ISSUE THREAD

**Issue by portokallidis** [riccox/meilisearch-ui#65]
**Is your feature request related to a problem? Please describe.**
Support for tenant tokens according to the [meili docs](https://www.meilisearch.com/docs/learn/security/tenant_tokens)

**Comment by riccox** [comment]
Fill add instance form with tenant token?

**Comment by portokallidis** [comment]
No i meant managing tenant keys like the api keys but it seems that they are short-lived so there is no need to. 
I will close the comment
