### ISSUE TITLE
Feature to load more indexes on indexes page

### ISSUE THREAD

**Issue by TheOneWhoKnokks** [riccox/meilisearch-ui#73]
Hi, first thank you for your package.

I want to know if it's possible to add a pagination or a scrolling feature to load more indexes data like on the task page.

Thank you

**Comment by riccox** [comment]
@TheOneWhoKnokks Hi,
Do u mean search result data of index?

**Comment by riccox** [comment]
@TheOneWhoKnokks Thanks!
Updated index list limit up to 1000 in new release version [v0.6.12](https://github.com/riccox/meilisearch-ui/releases/tag/v0.6.12).

It will take some time to run ci, you can try online demo & latest docker image after ci finished.

**Comment by TheOneWhoKnokks** [comment]
Thank you @riccox
