### ISSUE TITLE
Invalid multi platforms docker image

### ISSUE THREAD

**Issue by TonyRL** [riccox/meilisearch-ui#76]
**Describe the bug**
Only one platform of docker image is pushed. 

**To Reproduce**
1. Go to https://hub.docker.com/r/riccoxie/meilisearch-ui/tags
2. See error

**Expected behavior**
Each image should have multi arch support. 

**Screenshots**
N/A. 

**Environments (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
You can refer to https://github.com/docker/build-push-action/issues/846 for more details. According to [Multi-platform image with GitHub Actions](https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners), if you really want to build multi platform image which utilises job matrix you need to upload all the images as artifacts and then download them and merge them before pushing to Docker Hub. 
Otherwise, the old GitHub actions is good to go. 
https://github.com/riccox/meilisearch-ui/blob/63abf85acd7431d1a48ddc314f1bd43542ca8ff7/.github/workflows/docker-build-release.yaml#L29

**Comment by liebkne** [comment]
Got error `no matching manifest for linux/amd64 in the manifest list entries` when try to pull and build.

**Comment by riccox** [comment]
@TonyRL @liebkne Hi!
Fixed this in new release version v0.6.3 already.
