### ISSUE TITLE
After clicking the settings, the options keep jitter.

### ISSUE THREAD

**Issue by eryajf** [riccox/meilisearch-ui#8]
**Describe the bug**

Such as the title

**To Reproduce**

Download the latest version of the docker image. After starting, click the Settings button, and this problem occurs.

**Screenshots**

![dd](https://user-images.githubusercontent.com/33259379/218256129-1b937a4b-3e3b-4797-ae9d-8c64547a6a6b.gif)

**Environments (please complete the following information):**
 - OS: MacOS
 - Browser : chrome
 - Version: riccoxie/meilisearch-ui:latest

**Comment by riccox** [comment]
Hi @eryajf 
I can not reproduce this problem on my machine.
But I try to adjust the position of this dropdown menu.
Just check this live preview: https://meilisearch-p4qv1kc6u-riccox.vercel.app/
I'm glad to see your feedback if there is still same problem happened.

**Comment by riccox** [comment]
Hi @eryajf
I don't know if you have received my message, cause never got your feedback 2 days.
Close this issue with new release version [v0.1.1](https://github.com/riccox/meilisearch-ui/releases/tag/v0.1.1).
Just reopen this issue and leave your feedback if there is still same problem happened.

**Comment by eryajf** [comment]
Maybe it was my browser at that time, but now the problem is gone.

**Comment by riccox** [comment]
That's a good news for me.
Thanks for your feedback 💪.
