### ISSUE TITLE
Document/Index delete confirm button is hidden?

### ISSUE THREAD

**Issue by maoxuner** [riccox/meilisearch-ui#82]
**Describe the bug**
Document/Index delete dialog, confirm button can not be seen. Font color is white and backgroud is transparent/white

**To Reproduce**
1. Connect to a meilisearch instance from demo site https://meilisearch-ui.riccox.com/
2. Go to index settings, then danger zone, click "Delete This Index"
3. Delete dialog only shows a cancel button, confirm button is rendered but not can not be seen

**Expected behavior**
show confirm button with a "red" background

**Screenshots**
<img width="512" alt="image" src="https://github.com/riccox/meilisearch-ui/assets/104855611/4d2d9fa3-11d8-44ad-b6cf-b9458ed186ea">

**Environments (please complete the following information):**
 - OS: archlinux
 - Browser chrome
 - Version 118.0.5993.70 (x64)

**Additional context**
nothing

**Comment by riccox** [comment]
@maoxuner Thanks!
Fixed in new release version [v0.6.7](https://github.com/riccox/meilisearch-ui/releases/tag/v0.6.7).

It will take some time to run ci, you can try online demo & latest docker image after ci finished.

**Comment by maoxuner** [comment]
Another confirm button is not visible either and other issues. I've started an new issue #93

**Comment by riccox** [comment]
> @maoxuner Thanks! Fixed in new release version [v0.6.7](https://github.com/riccox/meilisearch-ui/releases/tag/v0.6.7).
> 
> It will take some time to run ci, you can try online demo & latest docker image after ci finished.

Got it!
