### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by TrNgTien** [riccox/meilisearch-ui#85]
I want to contribute to this source, how can I contribute? 

Which standards I have to follow?

**Comment by riccox** [comment]
@TrNgTien Hi,
I'm glad to see u wanna join this project.
I don't have a documented contribution standards to follow currently.
You can just follow the common git collaboration flow below.

1. Ensure your change has an issue! Find an [existing issue](https://github.com/riccox/meilisearch-ui/issues/) or [open a new issue](https://github.com/riccox/meilisearch-ui/issues/new).
* This is where you can get a feel if the change will be accepted or not.
2. Once approved, [fork the Meilisearch repository](https://help.github.com/en/github/getting-started-with-github/fork-a-repo) in your own GitHub account.
3. [Create a new Git branch](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-and-deleting-branches-within-your-repository)
4. Make your changes on your branch.
5. [Submit the branch as a Pull Request](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) pointing to the main branch of this repository. A maintainer should comment and/or review your Pull Request within a few days. Although depending on the circumstances, it may take longer.

**Comment by TrNgTien** [comment]
@riccox Thank a lot!!
