### ISSUE TITLE
Document delete confirm button is not visible in deleting dialog of query results

### ISSUE THREAD

**Issue by maoxuner** [riccox/meilisearch-ui#93]
**Describe the bug**

- [ ] Delete button translation error in query results list
- [ ] Delete button not visible in deleting dialog of query results

**To Reproduce**
1. Connect to a meilisearch instance from demo site [https://meilisearch-ui.riccox.com/](https://meilisearch-ui.riccox.com/)
2. Select any index which has documents, point to right bottom corner of the list, then actions buttons shown
3. Delete button shown at prev step was not translate (screenshot 1)
4. Click the "delete button", then the dialog shown
5. The confirm button is not visible (screenshot 2)

**Expected behavior**
1. delete button traslated
2. confirm button shown

**Screenshots**
<img width="1199" alt="1" src="https://github.com/riccox/meilisearch-ui/assets/104855611/3beb360d-e638-4d69-aa81-85c7019b8553">

<img width="1217" alt="2" src="https://github.com/riccox/meilisearch-ui/assets/104855611/fb0073f9-1a91-4958-a0c7-572237b000f2">

**Environments (please complete the following information):**
 - OS: archlinux
 - Browser chrome
 - Version 119.0.6045.105 (x64)

**Additional context**
related issue #82

**Comment by riccox** [comment]
@maoxuner Thanks!
Fixed in new release version [v0.6.8](https://github.com/riccox/meilisearch-ui/releases/tag/v0.6.8).

It will take some time to run ci, you can try online demo & latest docker image after ci finished.
